from pulumi_azure_native import authorization as auth

from storage import container_registry as cr
from project_config import platform_outputs

outputs = platform_outputs["iam"]["role_definitions"] = {}

if cr.registries.items():
    container_registry_role_def = auth.RoleDefinition(
        "container-registry-private-endpoint-connection-creator",
        role_name="ContainerRegistryPrivateEndpointConnectionCreator",
        permissions=[
            auth.PermissionArgs(
                # There is something weird with the ContainerRegistry actions.
                # Azure has not exposed the PrivateEndpointConnectionsApproval/action which we need.
                # Using the wildcard entry in the 'actions' list allows the action, then we filter
                # out all other actions that are not needed. The result is Actions - Not Actions = Effective Policy
                actions=["Microsoft.ContainerRegistry/registries/*"],
                not_actions=[
                    "Microsoft.ContainerRegistry/registries/read",
                    "Microsoft.ContainerRegistry/registries/write",
                    "Microsoft.ContainerRegistry/registries/delete",
                    "Microsoft.ContainerRegistry/registries/listCredentials/action",
                    "Microsoft.ContainerRegistry/registries/regenerateCredential/action",
                    "Microsoft.ContainerRegistry/registries/generateCredentials/action",
                    "Microsoft.ContainerRegistry/registries/importImage/action",
                    "Microsoft.ContainerRegistry/registries/getBuildSourceUploadUrl/action",
                    "Microsoft.ContainerRegistry/registries/queueBuild/action",
                    "Microsoft.ContainerRegistry/registries/listBuildSourceUploadUrl/action",
                    "Microsoft.ContainerRegistry/registries/scheduleRun/action",
                    "Microsoft.ContainerRegistry/register/action",
                    "Microsoft.ContainerRegistry/checkNameAvailability/read",
                    "Microsoft.ContainerRegistry/locations/deleteVirtualNetworkOrSubnets/action",
                    "Microsoft.ContainerRegistry/locations/operationResults/read",
                    "Microsoft.ContainerRegistry/operations/read",
                    "Microsoft.ContainerRegistry/registries/privateEndpointConnections/read",
                    "Microsoft.ContainerRegistry/registries/privateEndpointConnections/write",
                    "Microsoft.ContainerRegistry/registries/privateEndpointConnections/delete",
                    "Microsoft.ContainerRegistry/registries/privateEndpointConnectionProxies/validate/action",
                    "Microsoft.ContainerRegistry/registries/privateEndpointConnectionProxies/read",
                    "Microsoft.ContainerRegistry/registries/privateEndpointConnectionProxies/write",
                    "Microsoft.ContainerRegistry/registries/privateEndpointConnectionProxies/delete",
                    "Microsoft.ContainerRegistry/registries/privateEndpointConnectionProxies/operationStatuses/read",
                    "Microsoft.ContainerRegistry/registries/agentpools/read",
                    "Microsoft.ContainerRegistry/registries/agentpools/write",
                    "Microsoft.ContainerRegistry/registries/agentpools/delete",
                    "Microsoft.ContainerRegistry/registries/agentpools/listQueueStatus/action",
                    "Microsoft.ContainerRegistry/registries/artifacts/delete",
                    "Microsoft.ContainerRegistry/registries/builds/read",
                    "Microsoft.ContainerRegistry/registries/builds/write",
                    "Microsoft.ContainerRegistry/registries/builds/getLogLink/action",
                    "Microsoft.ContainerRegistry/registries/builds/cancel/action",
                    "Microsoft.ContainerRegistry/registries/buildTasks/read",
                    "Microsoft.ContainerRegistry/registries/buildTasks/write",
                    "Microsoft.ContainerRegistry/registries/buildTasks/delete",
                    "Microsoft.ContainerRegistry/registries/buildTasks/listSourceRepositoryProperties/action",
                    "Microsoft.ContainerRegistry/registries/buildTasks/steps/read",
                    "Microsoft.ContainerRegistry/registries/buildTasks/steps/write",
                    "Microsoft.ContainerRegistry/registries/buildTasks/steps/delete",
                    "Microsoft.ContainerRegistry/registries/buildTasks/steps/listBuildArguments/action",
                    "Microsoft.ContainerRegistry/registries/listPolicies/read",
                    "Microsoft.ContainerRegistry/registries/listUsages/read",
                    "Microsoft.ContainerRegistry/registries/metadata/read",
                    "Microsoft.ContainerRegistry/registries/metadata/write",
                    "Microsoft.ContainerRegistry/registries/operationStatuses/read",
                    "Microsoft.ContainerRegistry/registries/providers/Microsoft.Insights/diagnosticSettings/read",
                    "Microsoft.ContainerRegistry/registries/providers/Microsoft.Insights/diagnosticSettings/write",
                    "Microsoft.ContainerRegistry/registries/pull/read",
                    "Microsoft.ContainerRegistry/registries/push/write",
                    "Microsoft.ContainerRegistry/registries/quarantine/read",
                    "Microsoft.ContainerRegistry/registries/quarantine/write",
                    "Microsoft.ContainerRegistry/registries/runs/read",
                    "Microsoft.ContainerRegistry/registries/runs/write",
                    "Microsoft.ContainerRegistry/registries/runs/listLogSasUrl/action",
                    "Microsoft.ContainerRegistry/registries/runs/cancel/action",
                    "Microsoft.ContainerRegistry/registries/sign/write",
                    "Microsoft.ContainerRegistry/registries/taskruns/read",
                    "Microsoft.ContainerRegistry/registries/taskruns/write",
                    "Microsoft.ContainerRegistry/registries/taskruns/delete",
                    "Microsoft.ContainerRegistry/registries/taskruns/listDetails/action",
                    "Microsoft.ContainerRegistry/registries/tasks/read",
                    "Microsoft.ContainerRegistry/registries/tasks/write",
                    "Microsoft.ContainerRegistry/registries/tasks/delete",
                    "Microsoft.ContainerRegistry/registries/tasks/listDetails/action",
                    "Microsoft.ContainerRegistry/registries/updatePolicies/write",
                    "Microsoft.ContainerRegistry/registries/connectedRegistries/read",
                    "Microsoft.ContainerRegistry/registries/connectedRegistries/write",
                    "Microsoft.ContainerRegistry/registries/connectedRegistries/delete",
                    "Microsoft.ContainerRegistry/registries/eventGridFilters/read",
                    "Microsoft.ContainerRegistry/registries/eventGridFilters/write",
                    "Microsoft.ContainerRegistry/registries/eventGridFilters/delete",
                    "Microsoft.ContainerRegistry/registries/exportPipelines/read",
                    "Microsoft.ContainerRegistry/registries/exportPipelines/write",
                    "Microsoft.ContainerRegistry/registries/exportPipelines/delete",
                    "Microsoft.ContainerRegistry/registries/importPipelines/read",
                    "Microsoft.ContainerRegistry/registries/importPipelines/write",
                    "Microsoft.ContainerRegistry/registries/importPipelines/delete",
                    "Microsoft.ContainerRegistry/registries/pipelineRuns/read",
                    "Microsoft.ContainerRegistry/registries/pipelineRuns/write",
                    "Microsoft.ContainerRegistry/registries/pipelineRuns/delete",
                    "Microsoft.ContainerRegistry/registries/pipelineRuns/operationStatuses/read",
                    "Microsoft.ContainerRegistry/registries/replications/read",
                    "Microsoft.ContainerRegistry/registries/replications/write",
                    "Microsoft.ContainerRegistry/registries/replications/delete",
                    "Microsoft.ContainerRegistry/registries/replications/operationStatuses/read",
                    "Microsoft.ContainerRegistry/registries/scopeMaps/read",
                    "Microsoft.ContainerRegistry/registries/scopeMaps/write",
                    "Microsoft.ContainerRegistry/registries/scopeMaps/delete",
                    "Microsoft.ContainerRegistry/registries/scopeMaps/operationStatuses/read",
                    "Microsoft.ContainerRegistry/registries/tokens/read",
                    "Microsoft.ContainerRegistry/registries/tokens/write",
                    "Microsoft.ContainerRegistry/registries/tokens/delete",
                    "Microsoft.ContainerRegistry/registries/tokens/operationStatuses/read",
                    "Microsoft.ContainerRegistry/registries/webhooks/read",
                    "Microsoft.ContainerRegistry/registries/webhooks/write",
                    "Microsoft.ContainerRegistry/registries/webhooks/delete",
                    "Microsoft.ContainerRegistry/registries/webhooks/getCallbackConfig/action",
                    "Microsoft.ContainerRegistry/registries/webhooks/ping/action",
                    "Microsoft.ContainerRegistry/registries/webhooks/listEvents/action",
                    "Microsoft.ContainerRegistry/registries/webhooks/operationStatuses/read",
                    "Microsoft.ContainerRegistry/registries/providers/Microsoft.Insights/logDefinitions/read",
                    "Microsoft.ContainerRegistry/registries/providers/Microsoft.Insights/metricDefinitions/read",
                ],
            )
        ],
        assignable_scopes=[cr.resource_group.id],
        scope=cr.resource_group.id,
    )
    outputs["container_registry_private_endpoint_connection_creator"] = {
        "id": container_registry_role_def.id,
        "name": container_registry_role_def.role_name,
    }
